### ISSUE TITLE
怎么把插件弄到极路由主页

### ISSUE THREAD

**Issue by kroran** [Paull/hiwifi.easucks#107]
我昨天下了你的插件，你的插件直接在极路由的主页，我有一个安朗认证的插件，现在得用ssh登录路由器后台才能用，我想把那个插件也弄到路由器主页，怎么移植到那儿？

**Comment by Paull** [comment]
看项目源码的install.sh部分

kroran <notifications@github.com> 于 2019年6月1日周六 18:05写道：
