### ISSUE TITLE
大神辛苦了！由衷感谢！最近IP被封的情况很多，远期会不会加上V2ray模式呢？

### ISSUE THREAD

**Issue by a1314151617** [Paull/hiwifi.easucks#108]
vps的IP被封的情况很多，现在好用的是vmess套壳，所以问下远期会不会加上V2ray模式呢？
毕竟现在还在开发极路由插件的大神不多了。
非常感谢！

**Comment by Paull** [comment]
由于极路由商业运转前途不明，已转向研究openwrt。所以未来不会在目前的极路由上研究新插件，但有要能会有新固件。
