### ISSUE TITLE
极路由X无法安装

### ISSUE THREAD

**Issue by xinyuandd** [Paull/hiwifi.easucks#110]
curl easucks.cn|sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3618    0  3618    0     0    696      0 --:--:--  0:00:05 --:--:-- 35821
>>>正在下载FIFA助手...

curl: (35) ssl_handshake returned - PolarSSL: (-0x7780) SSL - A fatal alert message was received from our peer
>>>下载出问题了，请稍候再试，下载服务器确实偶有连不上的情况。

**Comment by xinyuandd** [comment]
手动下载脚本后，修改文件地址后就可以了。

**Comment by Paull** [comment]
good job

**Comment by ddzzhff** [comment]
@xinyuandd 现在还可以用改地址的方法吗？顺便问一下地址是多少谢谢了

**Comment by Paull** [comment]
@ddzzhff 
curl easucks.cn/20190930.geex|sh

**Comment by ddzzhff** [comment]
@Paull 大神，请问一下这个代码如果出现下载失败就是失效了吗，还是网络问题？谢谢了

**Comment by xinyuandd** [comment]
@ddzzhff 
--------------
NAME=FIFA助手
DOWNFROM=https://yourdownloadmirror/downloads
FILENAME=yourpackagename.tar.gz
echo ">>>正在下载$NAME..."
curl -# -k $DOWNFROM/$FILENAME -o /tmp/$FILENAME > /dev/null
if [ $? -eq 0 ]; then
---------------------
修改 $DOWNFROM/$FILENAME 
为实际的ip即可

**Comment by Paull** [comment]
@ddzzhff 目前没有网络问题，字别打错了就行
