### ISSUE TITLE
今天用锁中亚脚本永远是进南亚

### ISSUE THREAD

**Issue by ReneZYY** [Paull/hiwifi.easucks#116]
今天下午开始怎么也进不了中亚了，SSH连的节点没变，一直是香港的。curl easucks.cn/fifa20|sh
另外锁中亚把这个慢的服务器也锁了吧18.162.38.241。
万谢

**Comment by Paull** [comment]
- EA网络故障导致进不了中亚，等它恢复就好。
- 18.162.38.241也是中亚的服务器，pc和ps都有，xbox没有
