### ISSUE TITLE
域名中含有“node”字符在读取配置的时候会多出一个节点

### ISSUE THREAD

**Issue by Hk-Gosuto** [Paull/hiwifi.easucks#118]
看了下代码是文件ss_ajax.htm第59行
egrep 'ss_server_name|node'
匹配了node关键字导致的，我尝试改成了egrep 'ss_server_name|=node'可以规避这个问题，不过linux命令不太熟应该可以有更好的办法解决。

**Comment by Paull** [comment]
> 看了下代码是文件ss_ajax.htm第59行
> egrep 'ss_server_name|node'
> 匹配了node关键字导致的，我尝试改成了egrep 'ss_server_name|=node'可以规避这个问题，不过linux命令不太熟应该可以有更好的办法解决。

试试这个修复，以前对lua也一窍不通，用的是最麻烦的字符串拼接，现在直接用JSON变量了，应该不会碰到这么傻的问题了
