### ISSUE TITLE
自从升级后无法刷机了就一直显示下载

### ISSUE THREAD

**Issue by thofd** [Paull/hiwifi.easucks#13]
自从升级后无法刷机了就一直显示下载

**Comment by Paull** [comment]
能截个图看下吗？

thofd <notifications@github.com> 于 2017年11月16日周四 09:17写道：

**Comment by slfr** [comment]
从easucks.cn传输回来的脚本内容有点问题，如下所示：
echo ">>>正在下载$NAME..."
curl -# $DOWNFROM/$FILENAME -o /tmp/$FILENAME > /dev/null
这里的curl命令没有加-k参数强制去除ssl restrict。

服务端那边把脚本内容改一下应该就可以了。

**Comment by thofd** [comment]
@slfr @Paull 应该就是curl -k 的问题了，我马上试一下，感谢！

**Comment by thofd** [comment]
@Paull @slfr 
![default](https://user-images.githubusercontent.com/30772676/32978738-193e6e60-cc83-11e7-8df1-2c8faf1c426f.png)

**Comment by thofd** [comment]
测试完了还是不行呢

**Comment by Paull** [comment]
@thofd @slfr 服务器端脚本已加回-k参数，再试试？我要周二才能碰到电脑😜

**Comment by thofd** [comment]
@Paull @slfr 今天已经测试成功，Thank you so much!

**Comment by Paull** [comment]
@thofd 感谢反馈！不然会有更多的人安装不成功。
