### ISSUE TITLE
极1亲测可用

### ISSUE THREAD

**Issue by chiyich** [Paull/hiwifi.easucks#16]
有几个小小请求：
ip地址可不可以改为ipv6支持或者域名支持呢？
chacha20-ietf-poly1305加密方式不支持嘛

**Comment by Paull** [comment]
域名支持准备弄了
加密方式列表根据ss-redir -h提供，要支持其它估计得分别编译了，暂时没看到这些加密的好处，因为我这以玩FIFA为主，不受到干扰的话不加密都没事。

**Comment by chiyich** [comment]
chacha20-ietf-poly1305的抗干扰性更好的。。主要是ss提供的是这个。。

**Comment by Paull** [comment]
我查了下你要的加密方式要3.0以上的ss才支持，而我用的是2.4.7的，原因很简单：有现成的ipk，不用自己去编译。
回头研究研究cross compile

**Comment by Paull** [comment]
@chiyich 加密问题请跟进Issue #30
