### ISSUE TITLE
极路由3提示启动成功, 运行状态一直是未连接,确认 SS 服务是可用的.

### ISSUE THREAD

**Issue by TimorYang** [Paull/hiwifi.easucks#18]
![ab23d27d-46cc-40c7-afd0-c50bd625a706](https://user-images.githubusercontent.com/10718837/34331657-c15bc762-e963-11e7-8b93-8743c165e888.png)

能否查看到连接日志

**Comment by Paull** [comment]
很有可能是新功能引起的，服务器地址填IP别填域名试试。
日志方面还得进ssh手工看，界面上没有。
看看/tmp/easucks/ss.json里面是什么

**Comment by Paull** [comment]
@TimorYang 在ssh运行这个看下有什么

```cat /tmp/easucks/ss.json
```
记得给IP地址和密码打码
