### ISSUE TITLE
能不能增加一个功能？

### ISSUE THREAD

**Issue by 0ps** [Paull/hiwifi.easucks#21]
目前一个问题是：强制走代理的内置列表，提示文件未找到。

增加走代理能不能加上一个C段，0.0.0.0/24。？

**Comment by Paull** [comment]
IP方面没有强制列表，只有极路由自带的国内IP列表。
不是很明白0.0.0.0/24是干嘛用的，但可以考虑弄个自定义列表。

啪啪啪 <notifications@github.com> 于 2018年1月13日周六 18:13写道：

**Comment by Paull** [comment]
一直有这个想法，不知道真的有人需要，正在添加中8c58bdf

**Comment by Paull** [comment]
@0ps 最新版已支持自定义IP段走不走代理的功能，升级一下试试看
