### ISSUE TITLE
安装后，FAFI工具无法使用

### ISSUE THREAD

**Issue by rogerhanzhao** [Paull/hiwifi.easucks#26]
安装后，进入FAFI工具如下图，是初始化路由后安装的：
![image](https://user-images.githubusercontent.com/23209751/35143489-b6316b7a-fd3c-11e7-8d8f-118852baa7bf.png)

**Comment by rogerhanzhao** [comment]
空白一片啊，极路由版本，极2A HC5761A - 1.3.5.18462s

**Comment by Paull** [comment]
下个版本修复

**Comment by Paull** [comment]
@rogerhanzhao 已修复，请重新执行curl easucks.cn|sh
