### ISSUE TITLE
保存自定义域名后并没有立即生效，而是需要重启一次SS

### ISSUE THREAD

**Issue by Paull** [Paull/hiwifi.easucks#28]
保存自定义域名后，原来只是执行了dnsmasq的重启，看样子域名列表的生成这一块并不由dnsmasq启动脚本控制，需要改进/etc/init.d/easucks

**Comment by rogerhanzhao** [comment]
域名模式，是直接用内置域名，还是页面上列表里的？ 求解

**Comment by rogerhanzhao** [comment]
保存多个服务器，我保存不同的模式，线路选择时是如何处理的？ 负载均衡？

**Comment by Paull** [comment]
1.域名列表使用的是内置列表加上自定义列表
2.只能启用一个线路，我暂时还没有多线路的经验

rogerhanzhao <notifications@github.com> 于 2018年1月24日周三 17:24写道：

**Comment by Paull** [comment]
e34a5bf fixed this
