### ISSUE TITLE
加密方式可以添加chacha20-ietf-poly1305的支持吗？

### ISSUE THREAD

**Issue by mycsc** [Paull/hiwifi.easucks#30]
同上，目前我使用的代理服务仅提供chacha20-ietf-poly1305加密方式，希望可以添加该加密方式的支持。
非常感谢！

**Comment by Paull** [comment]
可以考虑，谁来教我一下交叉编译？用极路由的SDK？不想用别人编译好的二进制

CHU <notifications@github.com> 于 2018年2月3日周六 17:58写道：

**Comment by iKenzo** [comment]
同上，非常感谢

**Comment by Paull** [comment]
已经编译成功，下一步，整合
