### ISSUE TITLE
安装很简单，非常好用，然而有两个小问题

### ISSUE THREAD

**Issue by winglight** [Paull/hiwifi.easucks#32]
1.新增服务器时，是否能保留当前设置，而不是每次都使用默认的demo数据？
2.路由器启动时，那个自动启动的开关我以为会自动连接ss服务器，但是并没有，需要手动点击“连接”，如果仅仅这样，这个“自动启动”的选项到底有什么用呢？建议把自动连接服务器实现了

不管怎么样，感谢作者的辛苦付出！Great job！

**Comment by Paull** [comment]
1.这建议挺好
2.那个开关的正确名称应该是“开机自动主启动”

Wing Light <notifications@github.com> 于 2018年2月19日周一 08:50写道：

**Comment by Paull** [comment]
开机自动启动

**Comment by winglight** [comment]
@Paull 启动之后做个自动连接功能吧，这样就不用打开路由器UI手动连接了，另外，还有一个建议就是：
1.把当前服务器的连接状态显示在第一页，如果有当前网速或者流量统计就更好了
2.那几个服务器相关的“重连”、“停止”的按钮也最好放在第一页

以上，干吧带

**Comment by Paull** [comment]
你说的自动连接应该是已经有的吧，就是开机自动启动。
1.极路由后台自带网速和流量显示功能。
2.第一页界面年后有个版本，类似梅林的节点列表，每个节点后面有操作按钮。

Wing Light <notifications@github.com> 于 2018年2月19日周一 15:43写道：

**Comment by winglight** [comment]
我试了，开关路由器之后必须手动点击“启动”才能连接服务器

发自我的 iPhone

在 2018年2月20日，21:29，Paul Liu <notifications@github.com<mailto:notifications@github.com>> 写道：

你说的自动连接应该是已经有的吧，就是开机自动启动。
1.极路由后台自带网速和流量显示功能。
2.第一页界面年后有个版本，类似梅林的节点列表，每个节点后面有操作按钮。

Wing Light <notifications@github.com<mailto:notifications@github.com>> 于 2018年2月19日周一 15:43写道：

**Comment by winglight** [comment]
另外还有个问题就是：当点击了“启动”按钮之后，状态显示是“已连接”，但是这种情况下实际有可能是翻墙失败的，需要换个服务器再次连接――我之前使用的SS插件尽管功能简陋，但是可以检测当前的翻墙状态，我建议也加上这么一个“成功与否”的标志


________________________________

**Comment by Paull** [comment]
嗯，检测功能会增加的

Wing Light <notifications@github.com> 于 2018年2月21日周三 09:13写道：
