### ISSUE TITLE
請求開發白名單gfwlist

### ISSUE THREAD

**Issue by cyrilkong** [Paull/hiwifi.easucks#34]
感覺blacklist走代理的效果不如預期，可以的話考慮一下開發加入白名單雙運行

**Comment by Paull** [comment]
域名列表模式可以满足你的期望，它默认是黑名单模式，但你也可以把.com/.net/.org/.xxxxxx全都填到**强制走代理的域名**列表中，然后把你的白名单填到**强制不走代理的域名列表**中
