### ISSUE TITLE
 1.4.8.20462s  貌似不兼容

### ISSUE THREAD

**Issue by Finera** [Paull/hiwifi.easucks#39]
升级固件后重新折腾插件来试用的~目前测试SSH指令全部正常结束后路由主页没找到插件界面

**Comment by Finera** [comment]
4的增强版~修改哪里能具体点吗~或者告知下路径也行~~不懂PHP~N年前懂点DOS的基础罢了~

**Comment by Paull** [comment]
登录极路由的管理界面，然后打开的网址类似这样：
http://192.168.199.1/cgi-bin/turbo/;stok=d6fe43f960b1d8c2c11117792f0a95e1/admin_web/home
，把home这段改成easucks，注意不要复制我这个网址，d6fe43f960b1d8c2c11117792f0a95e1这段Token是每登录临时的。

Finera <notifications@github.com> 于 2018年3月9日周五 19:31写道：

**Comment by Finera** [comment]
OK~能理解~目前装了另一个插件先用着~下次更新时初始化一下再试试看~毕竟还是希望解决UDP和自动以白名单~这个是什么问题导致的呢？改后端能解决吗？

**Comment by Paull** [comment]
经测试，系统版本 : B70 - 1.4.8.20462s无此症状，请尝试恢复出厂后重新安装！
