### ISSUE TITLE
希望能支持UDP转发

### ISSUE THREAD

**Issue by xugui0821** [Paull/hiwifi.easucks#4]
还有个BUG，服务器别名不能打中文和符号 # 
![160144485568 1](https://cloud.githubusercontent.com/assets/21220256/21964776/97f9190e-db8d-11e6-851d-8d3c8448c608.png)

**Comment by Paull** [comment]
Sorry，目前是有意为之，这个别名是用作系统识别用的，我又不想多添加一栏，不然要填的东西太多。
添加时会有点别扭，但实际使用起来没人在乎这个，哈哈，以后准备改成支持中文的。

**Comment by Paull** [comment]
刚看到标题，之前只看内容了。。。至于UDP转发，在官方固件上是做不了了，所以才会有这么多的人为了这个去刷固件。

**Comment by qnmlgdsb** [comment]
https://github.com/qiwihui/hiwifi-ss

这边有个做了UDP转发的

**Comment by Paull** [comment]
@qnmlgdsb 你发的项目我仔细翻了翻，它这个选项只是启动时多加了个-u的参数，但是iptables和内核还是不支持TPROXY模块，无法完成UDP转发的任务。想要支持udp转发，目前唯一出路是刷第三方固件。

**Comment by Paull** [comment]
@xugui0821 服务器别名已支持中文，重新安装一下就行（不需要恢复出厂化），直接在ssh执行curl easucks.cn|sh
