### ISSUE TITLE
域名列表模式：gstatic.com 无法访问

### ISSUE THREAD

**Issue by sinkcup** [Paull/hiwifi.easucks#42]
![image](https://user-images.githubusercontent.com/4971414/38285962-6083a014-37f5-11e8-8b11-d26541ecf0a6.png)
![image](https://user-images.githubusercontent.com/4971414/38286198-9d3c7674-37f6-11e8-8e33-9a6062aa13ad.png)
![image](https://user-images.githubusercontent.com/4971414/38285981-7688fc24-37f5-11e8-912d-fd6251065684.png)

google正常访问，但 gstatic.com 无法访问，导致js之类的文件加载失败。

检查了“内置域名列表”，发现有 gstatic.com，重复添加到“强制走代理的域名”，还是不行。

网页模式 可以访问

![image](https://user-images.githubusercontent.com/4971414/38286289-34358e26-37f7-11e8-868c-c4b85f003db8.png)
![image](https://user-images.githubusercontent.com/4971414/38286311-5647bf70-37f7-11e8-9203-01da20638b63.png)

**Comment by sinkcup** [comment]
https://www.cpu-monkey.com/ 也无法访问

**Comment by Paull** [comment]
@sinkcup 确定在自定义域名里添加过不能访问的域名的话，试试直接在路由器和服务器上wget或curl一下是什么反应。你这个问题并不适合所有人，我这边不能复现。

**Comment by sinkcup** [comment]
@Paull 抱歉，gstatic.com 是由于我配了错误的hosts……

https://www.cpu-monkey.com/ 很奇怪，之前无法访问，现在也好了。

**Comment by Paull** [comment]
当时有可能是真的down掉了，多点测试一下，不要一个点有问题就上报。

sink cup <notifications@github.com> 于 2018年4月17日周二 21:40写道：
