### ISSUE TITLE
请问能加入ipv6功能吗?

### ISSUE THREAD

**Issue by voodoozz** [Paull/hiwifi.easucks#44]
服务器地址输入不能识别ipv6

**Comment by Paull** [comment]
服务器地址已支持IPv6，请到路由器ssh执行`curl easucks.cn|sh`升级最新版本。

**Comment by voodoozz** [comment]
谢谢!

**Comment by voodoozz** [comment]
刚升级了还是不行, 还是提示"请输入正确的域名或IP地址",并且不能保存.

**Comment by Paull** [comment]
浏览器缓存问题，Chrome的话可以F12勾选Disable cache，或换个浏览器

**Comment by voodoozz** [comment]
ok了! 多谢!

**Comment by voodoozz** [comment]
/etc/init.d/easucks 第34行好像没写完, 直接运行会连接不上

**Comment by Paull** [comment]
下午我看看，服务应该是启好了？

voodoozz <notifications@github.com> 于 2018年4月23日周一 11:43写道：

**Comment by voodoozz** [comment]
我用了以前的easucks文件，ipv6也没问题。 用新文件的不行，连接不上

**Comment by Paull** [comment]
好的，是bug就得消灭，下午我瞧瞧

voodoozz <notifications@github.com> 于 2018年4月23日周一 13:12写道：

**Comment by Paull** [comment]
@voodoozz /etc/init.d/easucks确实存在一些笔误，但都是ipv4部分的，已修正。
继续深入IPv6的启动发现，iptables要使用ip6tables，而ip6tables又没有NAT模块，看来你的Issue并没有只是可以填写IPv6的地址那么简单，由于没有IPv6实验环境，目前我只能先挂在这里了。
有能力有环境的话，欢迎提交PR！
目前我的思路是：参考/etc/init.d/easucks里iptables的部分，实现通过ip6tables把需要转发的流量转到ss-redir监听的端口。另外ss-redir和ss-server是否需要启用-6参数，我也没环境测试，我估计是需要的。有个难点就是，我前面提到过，ip6tables没有NAT模块！

**Comment by voodoozz** [comment]
我这边的使用状态是,可以连ipv6的ss server上网, 但是域名列表模式不起作用. 不知道现在工作在什么模式下,国内大部分是直连,国外有些是直连,有些是走了ss.

**Comment by Paull** [comment]
应该是根据目的地址是IPv4就照旧（各种模式），目的地址是IPv6就直连。

**Comment by voodoozz** [comment]
现在这个/etc/init.d/easucks文件还是有问题，还是会连不上，之前的是好的。
我不懂这个，但是37行最后的{没有}是有问题吗？

**Comment by Paull** [comment]
后面有内容的吧，你是用curl easucks.cn|sh来安装的？还怎么手工复制的脚本？

voodoozz <notifications@github.com> 于 2018年4月29日周日 下午3:21写道：

**Comment by voodoozz** [comment]
抱歉 好像我几次更新的时候出了 我完全恢复出厂在重新弄一次试试吧
谢谢 ：）

**Comment by Paull** [comment]
嗯嗯

voodoozz <notifications@github.com> 于 2018年4月29日周日 下午3:36写道：
