### ISSUE TITLE
这个插件是不会共享登陆的ss 呢？

### ISSUE THREAD

**Issue by yyw02110217** [Paull/hiwifi.easucks#49]
为毛我用了这个插件之后，架了2年的ss没多久就被墙了，废了老劲儿又重新架了2次，还是没过多久就被墙，都不敢用了！

**Comment by Paull** [comment]
这个插件是开源的

**Comment by yyw02110217** [comment]
哈哈哈，那估计是我被盯上了，算了，乖乖的我要！

**Comment by 1265578519** [comment]
@Paull @yyw02110217 插件长啥样，能在README.md中给出图片介绍？
