### ISSUE TITLE
节点列表里添加的服务器域名地址无法识别，提示请输入正确的域名或IP地址

### ISSUE THREAD

**Issue by Zwuwen** [Paull/hiwifi.easucks#50]
![0](https://user-images.githubusercontent.com/1666963/39414620-5c9d366e-4c6c-11e8-94a9-9f17d194b64f.PNG)
我的ss服务器域名是ru1-sta39.eo797.website，添加的时候提示请输入正确的域名或IP地址

**Comment by Zwuwen** [comment]
貌似结尾不能website

**Comment by Paull** [comment]
正则表达式对域名最后一段的限制是2-6位的字母(ノ๑`ȏ´๑)ノ︵⌨

`/^([a-z0-9-]+\.)*[a-z0-9-]+\.[a-z]{2,6}$/i.test(value);`

xiufeng <notifications@github.com> 于 2018年4月30日周一 上午11:58写道：

**Comment by Zwuwen** [comment]
好吧，谢谢。

**Comment by Paull** [comment]
重新安装一下，允许7位字母结尾的域名了

**Comment by Zwuwen** [comment]
收到，谢谢啦
