### ISSUE TITLE
您好，1.4.8版本无法用域名列表方式访问U2B和GOOGLE等网站

### ISSUE THREAD

**Issue by m1a2sep** [Paull/hiwifi.easucks#51]
首先非常感谢！然后我只要用域名方式，像U2B、TWITTER、GOOGLE等常用网站均无法访问，默认插件安装完成时的域名列表和我把这几个网站加入白名单后的列表都无法访问，但是网页模式就很正常，我是极4 1.4.8，非常感谢

**Comment by Paull** [comment]
目前我手上的没经过1.4.8直接升到1.4.10了，正常。请问你是哪个型号？回头我找找看

m1a2sep <notifications@github.com> 于 2018年5月9日周三 上午11:52写道：

**Comment by m1a2sep** [comment]
谢谢回复，我的是极4增强版，目前最高版本就是1.4.8.20462s

**Comment by Paull** [comment]
经测试，系统版本 : B70 - 1.4.8.20462s无此症状，请尝试恢复出厂后重新安装！

**Comment by Paull** [comment]
手工调试，在SSH试一下以下两个指令：
`nslookup google.com`和`curl google.com`
正常的输出如下：
![screenshot_2018-05-13_11-54-36](https://user-images.githubusercontent.com/273218/39963639-91f96700-56a4-11e8-86c1-11ec45afc936.png)

**Comment by m1a2sep** [comment]
谢谢您回复~~我试了上边方法跟图片显示的输出一样但是依然不能打开那些网站，我先用网页模式吧就，感谢您的帮忙~~

**Comment by Paull** [comment]
如果路由器上是这样的输出，那可能是终端有dns缓存，比如hosts之类的，多试几个终端对比下结果。
