### ISSUE TITLE
自动启动无效

### ISSUE THREAD

**Issue by qlphsk** [Paull/hiwifi.easucks#52]
设置了自动启动，但是没有效果

**Comment by Paull** [comment]
我这边各型号工作正常，帮忙调试下，在SSH输入`ls -l /etc/rc.d/|grep S99`
![screenshot_2018-05-13_11-59-44](https://user-images.githubusercontent.com/273218/39963676-3de4d612-56a5-11e8-82f8-e8ca63647aaa.png)
看看有没有S99easucks这项
