### ISSUE TITLE
安装加密升级包后，部分机型无法启动

### ISSUE THREAD

**Issue by do21** [Paull/hiwifi.easucks#53]
系统版本 : HC6361 - 1.2.5.16426s
用 `curl easucks.cn/ss_update|sh` 安装的，填好信息后无法启动

请问哪里可以看日志？

**Comment by Paull** [comment]
这个是升级加密的脚本，未升级前是可以用？

Benny Chen <notifications@github.com> 于 2018年5月18日周五 上午9:24写道：

**Comment by Paull** [comment]
没有日志，可以去掉命令最后三个字|sh，把脚本显示出来，再手工一句一句排错

Paull <liubaoluo@gmail.com> 于 2018年5月18日周五 上午10:00写道：

**Comment by do21** [comment]
测试了一下，没升级加密前可以连接的。

**Comment by do21** [comment]
我记得好像从1s开始就用的MTK的SoC了？极1是Atheros的……是这个原因么？

`root@Hiwifi:~# cat /proc/cpuinfo 
system type		: Atheros AR9330 rev 1
machine			: Turbo Wireless TW150V1 Board
processor		: 0
cpu model		: MIPS 24Kc V7.4
BogoMIPS		: 265.42
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 16
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0000, 0x0ff8, 0x0ff8, 0x0ff8]
ASEs implemented	: mips16
shadow register sets	: 1
kscratch registers	: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available
`

**Comment by do21** [comment]
是不是编译有问题了？我下载后，chmod +x 运行 ss-redir --help，提示这个

'./ss-redir: line 1: syntax error: unexpected "("'

**Comment by Paull** [comment]
应该是CPU不通用的原因了，看来我用极1s（老版）编译的并不适用所有型号， 所以在没有经过严格测试前我没有把它集成到稳定版里。
另外我也有提供编译脚本，有环境的可以自己编译一下：https://github.com/Paull/hiwifi.easucks/blob/master/cross_compile.sh

**Comment by Paull** [comment]
@do21 你发的这个源比较牛逼，省得编译了

**Comment by Pu240** [comment]
能否考虑加入添加自定义白名单功能？
感谢作者的努力！

**Comment by Paull** [comment]
有这个功能，或者你再具体点要白名单添加啥？

现在可以白域名、IP、MAC

Pu240 <notifications@github.com> 于 2018年9月7日周五 17:58写道：
