### ISSUE TITLE
正常安装、配置和运行插件，但访问google等域名时报域名无法解析

### ISSUE THREAD

**Issue by MarshalW** [Paull/hiwifi.easucks#54]
使用极路由2，系统版本： HC5861 - 1.4.10.20837s 

正常安装插件和加密升级包，配置支持SSR的MonoCloud服务，使用谷歌dns，启动服务后状态显示: `已连接(域名列表模式)`

在使用Chrome浏览器访问`https://www.google.com`时报错：

```找不到 www.google.com 的服务器 IP 地址。.. ERR_NAME_NOT_RESOLVED```

这一情况也出现在众多其他国外网站上。

在ssh登录路由器情况下，使用`wget`访问上述地址，报错是：

```bash
~# wget www.google.com
wget: bad address 'www.google.com'
```

请问如何解决，谢谢。

**Comment by Paull** [comment]
不支持ssr，只支持原版ss

**Comment by xukaifu** [comment]
极路由版本：  1.4.10.20837s  
ss-redir -h 显示结果正常  
在极路由上 wget www.google.com  正常

但是连上极路由后就是无法访问google

**Comment by Paull** [comment]
@xukaifu 多试几个终端，有可能终端有hosts一类的改动？
