### ISSUE TITLE
不小心让固件自动更新后无法安装此脚本，版本号：HC5761 - 1.4.11.21001s

### ISSUE THREAD

**Issue by QQQus** [Paull/hiwifi.easucks#55]
被坑爹的自动更新了HC5761 - 1.4.11.21001s版本

原来安装的脚本是这个，结果现在无法安装：
一键安装脚本（支持最新1.4.5.19222s固件）
cd /tmp &&curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh 回车

借助GOOGLE找到此处，想要用curl easucks.cn|sh命令一件安装这里的脚本
SSH反馈如下：
root@Hiwifi:/tmp# curl easucks.cn/-|sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to easucks.cn port 80: Connection refused
root@Hiwifi:/tmp# curl easucks.cn|sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to easucks.cn port 80: Connection refused

端口怎么关闭了，是极路由固件更新导致的还是这个一键安装地址也失效了........头大，想把梯子架在路由器里，不想用笔记本当梯子好累啊啊啊啊

**Comment by QQQus** [comment]
楼主小白一个，非程序猿，是个普通的伸手党，求程序员大大搭救则个

**Comment by Paull** [comment]
先恢复出厂，再root，最后进ssh执行一下curl easucks.cn|sh就行了

QQQus <notifications@github.com> 于 2018年6月1日周五 01:48写道：
