### ISSUE TITLE
无法使用“域名列表管理”功能

### ISSUE THREAD

**Issue by 0ps** [Paull/hiwifi.easucks#59]
升级完以后无法使用“域名列表管理”/
版本：HC5962 - 1.4.8.20462s 

![default](https://user-images.githubusercontent.com/3354553/41536190-6f95a02a-7337-11e8-8a07-8ff4444c91d9.PNG)

**Comment by Paull** [comment]
是全新安装吗？建议恢复出厂重新安装一遍

**Comment by 0ps** [comment]
第一下是升级安装的。后面直接恢复出厂设置全新安装，也是一样。

**Comment by Paull** [comment]
除了高级设置不能修改，普通的SS功能是正常的吧？

**Comment by Paull** [comment]
@0ps 有空约个时间远程看下

**Comment by 0ps** [comment]
其他一切正常，就是只有“域名列表管理”不能正常使用。留个方式

**Comment by Paull** [comment]
252825@qq.com，约个时间

啪啪啪 <notifications@github.com> 于 2018年6月26日周二 16:54写道：

**Comment by 0ps** [comment]
@Paull 今天再看的时候已经正常人，可能重启了几次的原因吧，感谢

**Comment by Paull** [comment]
那应该是你装过旧版本，浏览器有缓存，之前没想到。。。
