### ISSUE TITLE
极4增强版启动失败

### ISSUE THREAD

**Issue by xinyuandd** [Paull/hiwifi.easucks#6]
固件版本： 1.3.5.18462s 安装最新版本后，点击启动按钮，提示启动成功，但是无法使用。怎么破？

**Comment by Paull** [comment]
互联网能上，SS不能用是吧？方便远程让我调试一下吗？

**Comment by xinyuandd** [comment]
互联网能上，点击启用后，提示启动成功，然后连接状态依然是未连接，接着github就无法访问了。国内的依然可以。
1、是第一次安装。
2、安装后未更新固件。
3、没有

远程调试ok的。需要怎么协助？晚上或者周末才有时间哈。需要留什么联系方式？

**Comment by xinyuandd** [comment]
我邮箱：wwqdd1@126.com

**Comment by xinyuandd** [comment]
如何
联系与你？







在 2017-08-11 09:52:55，"Paul Liu" <notifications@github.com> 写道：


互联网能上，SS不能用是吧？方便远程让我调试一下吗？

**Comment by Paull** [comment]
加我QQ吧，252825。再约个时间。
极4上次测试是1.2.5也是远程的，我自己没有这个硬件：）

**Comment by xinyuandd** [comment]
QQ好友请求已发！296816230 芯苑








在 2017-08-11 11:18:03，"Paul Liu" <notifications@github.com> 写道：


加我QQ吧，252825。再约个时间。
极4上次测试是1.2.5也是远程的，我自己没有这个硬件：）
