### ISSUE TITLE
一个简单的小建议

### ISSUE THREAD

**Issue by wybb** [Paull/hiwifi.easucks#63]
服务器别名的取名限制建议减少，easucks.js中用正则去除了一些特殊字符其实没必要，特别是“.”，因为用ss服务器ip或者域名充当服务器名字很方便，没必要特意去取个其他名字，域名和ip都包含"."，虽然自己修改easucks.js也没问题，但是考虑方便，还是建议git的标准版上去除或减少一些名字限制

**Comment by wybb** [comment]
我试过了，只要easucks.js中修改了正则就能正常保存了

**Comment by Paull** [comment]
@wybb 推个PR过来嘛

**Comment by Paull** [comment]
well done & thank you! @wybb 
this issue is fixed in pull request #64 & commit 9a43567
