### ISSUE TITLE
能否考虑加入自定义白名单功能？

### ISSUE THREAD

**Issue by Pu240** [Paull/hiwifi.easucks#71]
感谢作者付出的努力，十分感谢。

**Comment by Paull** [comment]
现在已有域名白名单、IP白名单、MAC白名单功能。

如果是其它东西，你再具体点要给白名单添加什么？

Pu240 <notifications@github.com> 于 2018年9月7日周五 17:59写道：

**Comment by Pu240** [comment]
有的时候发现一些网站没被白名单收录，所以只能开全局，所以希望能够加一个往白名单手动添加域名的功能，类似于shadowsocks客户端的修改pac文件功能。

**Comment by Paull** [comment]
有这个功能的，「首页」->「FIFA助手」->高级设置的「域名列表管理」

**Comment by Pu240** [comment]
啊看到了，谢谢
