### ISSUE TITLE
极1S安装插件后DHCP功能出现异常

### ISSUE THREAD

**Issue by Pu240** [Paull/hiwifi.easucks#72]
DHCP功能页显示为白板，必须要点击关闭按钮后再启动才能显示可操作项，如图：
![20180910084607](https://user-images.githubusercontent.com/16776635/45271028-100ba600-b4d6-11e8-8f00-af13ead152ba.jpg)
![20180910084623](https://user-images.githubusercontent.com/16776635/45271029-100ba600-b4d6-11e8-988b-9d70e5b3059e.jpg)
但是即使DHCP页能显示后，也不能进行mac地址与ip绑定，填入ip地址会提示ip地址不正确。
路由器和系统版本是极1S、HC5661A - 1.4.10.20837s，谢谢。

**Comment by Paull** [comment]
建议恢复出厂再重新安装试试，我现在已经升到1.4.11了，不能复现这个问题

**Comment by Paull** [comment]
今天试了极1S（1.4.11）和极3S（1.4.10）都没有这个问题，还是推荐你恢复出厂试下。
