### ISSUE TITLE
域名列表模式无法打开网页

### ISSUE THREAD

**Issue by lzhs168** [Paull/hiwifi.easucks#74]
在应用域名列表模式时为何未能打开域名列表网页？是插件未完善还是设置上的问题？

**Comment by Paull** [comment]
插件目前已是稳定版，很多设备已经跑了一年以上了。
尝试换个SS吧，也可能是服务器节点问题。

**Comment by lzhs168** [comment]
我是用自己假设的Google vps，有没有需要在服务器上加什么设置？

Paul Liu <notifications@github.com> 于 2018年9月13日周四 15:29写道：

**Comment by Paull** [comment]
必须是SS不是SSR，然后参数没问题并且IP能通就好了。服务器上并没有特殊要求，推荐问别人要个别家的VPS架的服务器试下。
