### ISSUE TITLE
B70 - 1.4.8.20462版本无法安装？

### ISSUE THREAD

**Issue by leosheng2018** [Paull/hiwifi.easucks#75]
B70 - 1.4.8.20462版本无法安装？
![wechatimg698](https://user-images.githubusercontent.com/43231512/45472544-195f7180-b767-11e8-896e-5c98d9b66e5a.jpeg)

**Comment by Paull** [comment]
B70支持且可以安装，这个curl error 7是连接不上服务器的提示，可以稍候尝试。
