### ISSUE TITLE
google.ca打不开呢,用电脑版ss就可以打开,同一台服务器

### ISSUE THREAD

**Issue by thofd** [Paull/hiwifi.easucks#8]
google.ca打不开呢,用电脑版ss就可以打开,同一台服务器

**Comment by Paull** [comment]
可以自定义域名，可能google.ca不在内置的gfwlist里

**Comment by thofd** [comment]
太感谢了,我一发就得到大侠的回复,,我今天把google.ca加入到强制转发列表里面,但是还是打不开,搞不清是什么原因

**Comment by thofd** [comment]
> 
您的连接不是私密连接

攻击者可能会试图从 www.google.ca 窃取您的信息（例如：密

码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_COMMON_NAME_INVALID
 
自动向 Google 发送一些系统信息和网页内容，以帮助检测危险

应用和网站。隐私权政策
重新加载隐藏详情
www.google.ca 通常会使用加密技术来保护您的信息。Google 

Chrome 此次尝试连接到 www.google.ca 时，此网站发回了异

常的错误凭据。这可能是因为有攻击者在试图冒充 

www.google.ca，或 Wi-Fi 登录屏幕中断了此次连接。请放心，

您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数

据交换便停止了连接。

您目前无法访问 www.google.ca，因为此网站使用了 HSTS。网

络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常

。
>

**Comment by Paull** [comment]
你这个错误状态像是被中间人攻击了，证书不正确，而不是连接不上。
