### ISSUE TITLE
插件无法自启动

### ISSUE THREAD

**Issue by 0ps** [Paull/hiwifi.easucks#80]
重启路由器以后，插件无法自启动，进程有。

>  5177 root      3132 S    /usr/bin/ss-redir -c /tmp/easucks/ss.json -f /var/run/easucks.pid

要手动在【运行状态】里点重启才能成功。

**Comment by Paull** [comment]
有进程又无法自启动是什么情况，就是进程启动了但是无法访问？手动重启后又可以访问了？

**Comment by 0ps** [comment]
是的
