### ISSUE TITLE
安装后没有FIFA19锁服选项

### ISSUE THREAD

**Issue by stefanis5454** [Paull/hiwifi.easucks#87]
路由器已升级最新固件HC5761 - 1.4.11.21001s
完全按照教程安装 curl easucks.cn|sh
安装后节点设置高级选项下没有FIFA19锁服选项
![image](https://user-images.githubusercontent.com/31231433/47924871-c2208680-def7-11e8-88c0-8c85f59f43ea.png)

**Comment by Paull** [comment]
有BUG，Issue #88 ，暂时退回老版本，锁中亚请使用手动的方法：Issue #77
