### ISSUE TITLE
极路由插件带的锁服功能有BUG，已退回老版本

### ISSUE THREAD

**Issue by Paull** [Paull/hiwifi.easucks#88]
会影起Issue #80 插件无法自启的BUG，故暂时退回老版本，玩家请使用手动脚本锁中亚：Issue #77

**Comment by UniRider** [comment]
我也是装了助手，但不显示锁服开关。这个助手很直观，盼望大神更新。

**Comment by Paull** [comment]
暂时先用手动刷脚本的方法

UniRider <notifications@github.com> 于 2018年11月3日周六 17:28写道：
