### ISSUE TITLE
不能安装FIFA19强制锁服脚本

### ISSUE THREAD

**Issue by UniRider** [Paull/hiwifi.easucks#89]
极路由1s（老版5661），最新官方固件，裸连，执行指令后，显示failed
![easucks](https://user-images.githubusercontent.com/44722935/47950444-76202100-df8d-11e8-9404-3de722b6c749.png)

**Comment by Paull** [comment]
已修复

UniRider <notifications@github.com> 于 2018年11月3日周六 17:26写道：

**Comment by UniRider** [comment]
太棒了，锁服成功，多谢
