### ISSUE TITLE
为啥我在强制走代理的域名列表添加google.com不能强制走代理

### ISSUE THREAD

**Issue by Skw172389774** [Paull/hiwifi.easucks#96]
为啥我在强制走代理的域名列表添加google.com不能强制走代理

**Comment by Skw172389774** [comment]
如果用全局模式则可以访问https://www.google.com/  域名模式不管如何添加都访问不了

**Comment by Skw172389774** [comment]
用游戏模式就好了

**Comment by Paull** [comment]
请检查本地dns缓存或hosts，或换个干净的设备

Skw172389774 <notifications@github.com> 于 2019年1月3日周四 23:04写道：
