### ISSUE TITLE
B70 现在安装新版本都没办法用了，格式化重新安装也没办法用。

### ISSUE THREAD

**Issue by love768952693** [Paull/hiwifi.easucks#99]
B70 现在安装新版本都没办法用了，格式化重新安装也没办法用。

密码好像大余16位也不保存了。。。。

**Comment by Paull** [comment]
固件版本多少？1.5以上了？

**Comment by love768952693** [comment]
就是最新的固件，昨晚折腾了好久，本来想试试新的加密模式的。。。。

**Comment by Paull** [comment]
具体版本号多少

love768952693 <notifications@github.com> 于 2019年2月13日周三 17:45写道：

**Comment by love768952693** [comment]
刚又特意刷回来了，看了下

系统版本 : HC5962 - 1.4.8.20462s

**Comment by Paull** [comment]
我也是B70 1.4.8，密码是不能有特殊字符，尤其是=和.

love768952693 <notifications@github.com> 于 2019年2月14日周四 00:47写道：

**Comment by Paull** [comment]
你的情况应该是属于ss不兼容

Paull <liubaoluo@gmail.com> 于 2019年2月14日周四 00:57写道：

**Comment by love768952693** [comment]
大佬我是 

版本低了？还是高了。

**Comment by love768952693** [comment]
今晚又看了下，打开了你的配置文件路径，密码只能保存10位，初步估计是正则提取的时候遇到了 $ 这个符号，建议大佬修改成获取 键入框的全部值。

目前通过SHH 手动方式修改的密码，然后重启服务，还是不行，不知道是不是加密协议不支持，还是配置文件有多处。

使用的协议是：aes-256-gcm


config 20181008 'version'

config node 'server1'
	option ss_server_name 'usa'
	option ss_server_ipad 'X.X.X.X.X.'
	option ss_server_port 'X.X.X.'
	option ss_server_pass 'XXXXXXX$XXXX'

**Comment by Paull** [comment]
这个协议默认版本没得选的吧，执行过加密升级没有。

ss-redir -h可以看支持的加密算法列表

love768952693 <notifications@github.com> 于 2019年2月14日周四 03:56写道：

**Comment by love768952693** [comment]
执行过了，再添加的。然后再修改的配置文件，但是就是不生效。

**Comment by love768952693** [comment]
![image](https://user-images.githubusercontent.com/24494048/52797858-b83f1f80-30b1-11e9-89e0-66ad1ef92d0b.png)
执行了看了下，目测是支持的~！！！

**Comment by Paull** [comment]
插件界面启动后，cat /tmp/easucks/ss.json看看有没有异常，然后killall ss-redir，手动启一个ss-redir -c
/tmp/easucks/ss.json -v
看看有什么输出

love768952693 <notifications@github.com> 于 2019年2月14日周四 23:39写道：

**Comment by love768952693** [comment]
好，我周天回来试试，这周有事去了。

**Comment by love768952693** [comment]
另外，楼主我问下，我们有办法直接把被人已经做好的OpenWrt 插件，放进去吗？

还带了去广告

比如这个 https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=331639&orderby=dateline

这个已经集成了规则更新，普通和R的支持，还有其它的，好像蛮全的，虽然不是最新版。

**Comment by Paull** [comment]
这是个固件，用不了，得从源码编译

love768952693 <notifications@github.com> 于 2019年2月15日周五 12:28写道：
